"""Capstone translation, width validation and small explicit P0 feature exclusions."""

import capstone as cs
from dataclasses import replace
from capstone import arm_const as arm

from armstride.architecture.arm import PROFILE, validate_profile
from armstride.domain.models import MAX_INSTRUCTIONS, DecodeMetadata, DomainError, Instruction, Operand, validate_range

CONDITIONS = {getattr(arm, "ARM_CC_" + name.upper()): name for name in
              ("eq", "ne", "hs", "lo", "mi", "pl", "vs", "vc", "hi", "ls", "ge", "lt", "gt", "le")}
SHIFTS = {getattr(arm, name): name.removeprefix("ARM_SFT_").lower()
          for name in dir(arm) if name.startswith("ARM_SFT_") and name != "ARM_SFT_INVALID"}
SYSTEM_OPERATIONS = {"mrs", "msr", "cps", "setend", "svc", "hvc", "smc", "bkpt", "udf",
                     "dmb", "dsb", "isb", "wfe", "wfi", "sev", "sevl", "eret"}
INSTRUCTION_NAMES = frozenset(name.removeprefix("ARM_INS_").lower()
                              for name in dir(arm) if name.startswith("ARM_INS_"))


def is_bare_mnemonic(text: str) -> bool:
    """Reject mnemonic-only lines masquerading as fromelf symbol metadata."""
    name = text.lower().removesuffix(".w").removesuffix(".n")
    forms = [name]
    if name[-2:] in (*CONDITIONS.values(), "cs", "cc", "al"):
        forms.append(name[:-2])
    return any(form in INSTRUCTION_NAMES or form.removesuffix("s") in INSTRUCTION_NAMES for form in forms)


def register_name(instruction, register: int) -> str | None:
    name = instruction.reg_name(register) if register else None
    return {"sb": "r9", "sl": "r10", "fp": "r11", "ip": "r12"}.get(name, name)


def feature_exclusion(operation: str, groups: tuple[str, ...]) -> str | None:
    if operation == "it":
        return "Thumb IT blocks are outside P0."
    if operation.startswith(("ldrex", "strex")) or operation == "clrex":
        return "Exclusive monitor state is outside P0."
    if operation in SYSTEM_OPERATIONS or operation.startswith(("rfe", "srs")) or "privilege" in groups:
        return "System state and exception execution are outside P0."
    if any(group.startswith(("neon", "vfp")) for group in groups) or operation.startswith("v"):
        return "SIMD and floating-point state are outside P0."
    if operation.startswith(("mcr", "mrc", "mrrc", "cdp", "ldc", "stc")):
        return "Coprocessor state is outside P0."
    return None


def operand_record(instruction, operand) -> Operand:
    shift = (SHIFTS[operand.shift.type], operand.shift.value) if operand.shift.type in SHIFTS else None
    if shift and shift[0].endswith("_reg"):
        shift = (shift[0], register_name(instruction, operand.shift.value))
    common = {"shift": shift, "subtracted": operand.subtracted}
    if operand.type == arm.ARM_OP_REG:
        return Operand("register", register=register_name(instruction, operand.reg), **common)
    if operand.type == arm.ARM_OP_IMM:
        return Operand("immediate", immediate=operand.imm, **common)
    if operand.type == arm.ARM_OP_MEM:
        memory = operand.mem
        return Operand("memory", memory=(register_name(instruction, memory.base),
                       register_name(instruction, memory.index), memory.disp), **common)
    return Operand("other", **common)


class ArmDecoder:
    def __init__(self, mode: str):
        validate_profile(PROFILE, mode)
        self.mode = mode
        self._decoder = cs.Cs(cs.CS_ARCH_ARM, cs.CS_MODE_ARM if mode == "arm" else cs.CS_MODE_THUMB)
        self._decoder.detail = True

    def decode_stream(self, address: int, raw_bytes: bytes) -> tuple[Instruction, ...]:
        """Normalize a complete generated stream, without guessing source locations."""
        validate_range(address, len(raw_bytes), "invalid_encoding")
        instructions = []
        consumed = 0
        try:
            for decoded in self._decoder.disasm(raw_bytes, address):
                if len(instructions) == MAX_INSTRUCTIONS:
                    raise DomainError("input_limit", "Too many instructions.")
                instruction = self.decode(decoded.address, bytes(decoded.bytes), None, "", "")
                instructions.append(replace(instruction, display_text=instruction.decoded_text))
                consumed += instruction.size
        except cs.CsError as error:
            raise DomainError("invalid_encoding", f"Decoder rejected stream: {error}") from error
        if consumed != len(raw_bytes):
            raise DomainError("invalid_encoding", "Generated bytes contain undecodable or incomplete instructions.")
        return tuple(instructions)

    def decode(self, address: int, raw_bytes: bytes, source_line: int | None,
               source_text: str, display_text: str) -> Instruction:
        validate_range(address, len(raw_bytes), "invalid_encoding")
        alignment = 4 if self.mode == "arm" else 2
        if address % alignment:
            raise DomainError("invalid_encoding", "Instruction address is misaligned.", address=address)
        if len(raw_bytes) not in ((4,) if self.mode == "arm" else (2, 4)):
            raise DomainError("invalid_encoding", "Invalid instruction byte count.")
        try:
            decoded = next(self._decoder.disasm(raw_bytes, address, count=1), None)
            if decoded is None or decoded.size != len(raw_bytes):
                raise DomainError("invalid_encoding", "Bytes must decode as exactly one complete instruction.")
            operation = decoded.insn_name()
            groups = tuple(decoded.group_name(group) for group in decoded.groups)
            reads, writes = decoded.regs_access()
            metadata = DecodeMetadata(
                operation, CONDITIONS.get(decoded.cc),
                tuple(operand_record(decoded, operand) for operand in decoded.operands), groups,
                tuple(register_name(decoded, register) for register in reads),
                tuple(register_name(decoded, register) for register in writes), decoded.update_flags, decoded.writeback)
            exclusion = feature_exclusion(operation, groups)
            if self.mode == 'arm' and metadata.updates_flags and 'pc' in metadata.registers_written:
                exclusion = 'Exception-return state is outside P0.'
            return Instruction(address, raw_bytes, self.mode, source_line, source_text, display_text,
                               f"{decoded.mnemonic} {decoded.op_str}".strip(), metadata,
                               feature_exclusion=exclusion)
        except cs.CsError as error:
            raise DomainError("invalid_encoding", f"Decoder rejected instruction: {error}") from error
